### ISSUE TITLE
v1 planned ?

### ISSUE THREAD

**Issue by maidmaid** [spatie/period#6]
Hi ! Your package looks really cool, thanks for it !

> This package is still a work in progress.

I'd need something like it in my company's projects. Is there any plan for a first stable release ? If you open some tickets, we could help you for releasing it faster.

**Comment by brendt** [comment]
I'm using v0.2.0 in one of our projects already. The reason I haven't tagged 1.0.0 yet is because I want to be sure all edge cases I encounter in a real project are accounted for. As far as I'm concerned, I won't add anything breaking before 1.0.0, I just want it to be tested a little more.

So the best thing you can do is pull in 0.2.0 and plug in into your project, and let know whether things need to be addressed before tagging 1.0.0. 

I'm planning on tagging a stable release somewhere next week or the week thereafter.
